### ISSUE TITLE
"At least" or bounded soft constraints

### ISSUE THREAD

**Issue by hunhoffe** [vmware/declarative-cluster-management#155]
### Is your feature request related to a problem? Please describe.

I'd like an intuitive way (or an example) to write constraints such as "keep this value between the bounds of 3 and 5" or "at least n if possible, but then minimize the amount greater than n" (e.g., as close to n as possible). 

### Describe the solution you'd like

Instead of minimize, having some query like absolute value near to? Or an "atleast" abstraction? I admittedly don't have a great idea of what a reasonable solution would look like.

### Describe alternatives you've considered

You could have two constraints (a lightly weighted minimize + a strongly weighted check count == n) which kind of captures the logic of "at least" but isn't really exact at all.

### Additional context

I'm interested in trying to balance replication with locality when using DCM to schedule tasks on cores of memory allocations across nodes. Replication gives me the desire for the "at least" mechanism; locality gives me the desire for a "no more than" mechanism.

**Comment by lalithsuresh** [comment]
@hunhoffe as I think about this, I believe the alternative you've described is the best possible way to express these constraints. I believe the bigger problem here are the intermediate variables you are defining the constraints on, right (that is, it requires a join against a variable column, which blows up the model size)?

**Comment by lalithsuresh** [comment]
So basically, something like this:

```
CREATE CONSTRAINT soft_bounds AS
SELECT * FROM t
MAXIMIZE weight1 * (t.var >= 3 AND t.var <= 5)

CREATE CONSTRAINT soft_bounds AS
SELECT * FROM t
MAXIMIZE  weight2 * (n - t.var)
```

**Comment by hunhoffe** [comment]
Thank you for the concrete example of what this might look like! I'll start by working with this solution
