### ISSUE TITLE
Rewrite affinity/anti-affinity views

### ISSUE THREAD

**Issue by faria-kalim** [vmware/declarative-cluster-management#30]
Users provide labels that describe which nodes pods are affine and anti-affine to. These labels help shortlist nodes that are whitelisted and blacklisted for the pod. Currently, we combine this information to create a final whitelist of nodes for the pod. This can be problematic if the user only provides us with a blacklist; then, we build a view that gives us the set of rows = {all nodes - blacklisted nodes}. This list is large and can be expensive to pull out. Instead, we can try to make use of the fact that the blacklist is usually small and rewrite our constraint to ignore the blacklisted nodes while placing the pod.

**Comment by lalithsuresh** [comment]
Partially addressed by use of array columns, and subsequent patches that split queries into multiple ones that each use an index.
