### ISSUE TITLE
k8s-scheduler: Pod.Name probably should not be used as primary key

### ISSUE THREAD

**Issue by reith** [vmware/declarative-cluster-management#59]
Since different namespaces can have different Pods by the same name, it looks better to define [pods_info](https://github.com/vmware/declarative-cluster-management/blob/066ff620f8272cdbecb26f1a79975f3434b4ba5d/k8s-scheduler/src/main/resources/scheduler_tables.sql#L27) table's primary key as Pod.UUID and have foreign keys based on UUID. I see UUID is missing from pods_info, if there is a reason behind that, defining a compound key of Pod.Name and Pod.Namespace looks more appropriate.

**Comment by lalithsuresh** [comment]
Thanks for the report @reith! We're currently working on an overhaul of the DB side to integrate with an incremental engine, and this is one of the changes we're lining up on that side.

**Comment by lalithsuresh** [comment]
Until then, if this is a showstopper for you, I can work on adding the UUID field to pods_info (or merge a patch if you already have one).

**Comment by reith** [comment]
Thanks!

I'm just getting familiar with DCM (at looks really awesome, thanks!) and I don't plan to use it for scheduling Pods. So, it's not a big issue.

**Comment by lalithsuresh** [comment]
Fixed by #72
