### ISSUE TITLE
CapacityConstraint scale and limits

### ISSUE THREAD

**Issue by reith** [vmware/declarative-cluster-management#75]
`capacityConstraint` demands and capacities are `Integers` and if not normalized can overflow soon. In fact `k8s-scheduler` implementation will probably fail to schedule Pods requesting memory more than `4Gi`. It seems `ortools` can work with Longs, in that case, do changing them have negative impact on solving performance?
Currently, I scale down values in my controller before storing them in database, but maybe implementation can get enhanced. Also [there is a](https://github.com/vmware/declarative-cluster-management/blob/22d0ad9e6cadcf648933faf8483aacf1c057fa49/dcm/src/main/java/com/vmware/dcm/backend/ortools/Ops.java#L512) `scale` factor [which further reduces](https://github.com/vmware/declarative-cluster-management/blob/22d0ad9e6cadcf648933faf8483aacf1c057fa49/dcm/src/main/java/com/vmware/dcm/backend/ortools/Ops.java#L563) overflow limit by 1000. If `capacityConstraint` is expected to work just for Integer, it's good to detect and throw exceptions in generated code iteration. It's better to fail model creation if database schema suggest that overflow is possible.

Also, there are two possible division by zero cases, [here](https://github.com/vmware/declarative-cluster-management/blob/22d0ad9e6cadcf648933faf8483aacf1c057fa49/dcm/src/main/java/com/vmware/dcm/backend/ortools/Ops.java#L590)  when a node has no capacity and [here](https://github.com/vmware/declarative-cluster-management/blob/22d0ad9e6cadcf648933faf8483aacf1c057fa49/dcm/src/main/java/com/vmware/dcm/backend/ortools/Ops.java#L563)  when some capacity in all nodes are zero. I surprised by second case because in my scenario the `capacityConstraint` been called for a different task that I wasn't solving model for it - the Policy that called was for scheduling Pods but I didn't have any Pod in database or model - So all demands where zero there and probably the function could have returned sooner.

**Comment by lalithsuresh** [comment]
@reith Thanks for reporting this! Good catch! 

Yes, it helps to scale down values before you use capacity-constraints. We already attempt this somewhat in Utils.convertUnit(), but I agree this should be better handled.

Besides that, there is no good reason to stay within Integer domain for capacity constraints, given that or-tools works with longs by default. I'll incorporate that change as well.

I'll have a fix in in the next day or two.

Could you elaborate better on what happened with the 2nd divide by zero case? Was it caused by demands and capacities for some resource being zeroes?

- [ ] Use Longs instead of Integers for capacityConstraint inputs
- [ ] Revisit the use of a scale parameter, that further causes overflow problems
- [ ] Fix the two divide by zero cases, caused by trying to normalize capacities

**Comment by reith** [comment]
> Could you elaborate better on what happened with the 2nd divide by zero case? Was it caused by demands and capacities for some resource being zeroes?

It was because all nodes capacity for one `capacityConstaint` where zero making `capacity` zero in [this line](https://github.com/vmware/declarative-cluster-management/blob/22d0ad9e6cadcf648933faf8483aacf1c057fa49/dcm/src/main/java/com/vmware/dcm/backend/ortools/Ops.java#L561) for that constraint, but in my case it looked to me unnecessary to reach to that line because all demands where zero too and that function could return sooner. And it seems demands where zero because capacity constraint has been called for totally another task. That constraint was for scheduling Pods but I didn't have any Pod in database except that Policy was compiled in model.

**Comment by lalithsuresh** [comment]
@reith I'm working on these changes in the issue-75 branch here: https://github.com/vmware/declarative-cluster-management/tree/issue-75

Are you invoking capacity constraints with integer columns right now? Would you want to also invoke them with say, bigint columns?

**Comment by lalithsuresh** [comment]
@reith could you confirm if the latest changes to master work for you?
https://github.com/vmware/declarative-cluster-management/commit/d9def4206e2368982304ff301b443eb1be597270

**Comment by reith** [comment]
@lalithsuresh 

Thanks!

I'm invoking it with bigint columns but values are 31bit (to mitigate previous overflow).

Isn't it better to use `allMatch` instead of `anyMatch` [here](https://github.com/vmware/declarative-cluster-management/blob/d9def4206e2368982304ff301b443eb1be597270/dcm/src/main/java/com/vmware/dcm/backend/ortools/Ops.java#L505) and [line #497](https://github.com/vmware/declarative-cluster-management/blob/d9def4206e2368982304ff301b443eb1be597270/dcm/src/main/java/com/vmware/dcm/backend/ortools/Ops.java#L497)? Not just more intended it looks, `anyMatch` makes model fail on empty demands which happens when `capacityConstraint` is about resources that does not exist in model.

**Comment by lalithsuresh** [comment]
@reith all three are correct observations. Thanks! https://github.com/vmware/declarative-cluster-management/commit/6c47b16da07b6bb30f58f9041c8007020d4ca7ba

Regarding why the tests missed the last case, that particular style of sum is for a special case of sums over constants without any dependency on a variable, which is rarely needed in actual models. I've added a test to catch that nevertheless!

**Comment by reith** [comment]
Great work, thanks!
